---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  labels:
    app: datamart
data:
  elasticsearch.cluster_name: "docker-cluster"
  elasticsearch.heap_size: "4g"
  api_url: http://192.168.99.100:30081/api/v1
  frontend_url: http://192.168.99.100:30080
  nominatim_url: http://nominatim:8080/
  custom_fields: ""
  redis.conf: |
    maxmemory 500mb
    maxmemory-policy allkeys-lru
