---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: auctus
    what: rabbitmq
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: auctus
      what: rabbitmq
  template:
    metadata:
      labels:
        app: auctus
        what: rabbitmq
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: rabbitmq
        image: quay.io/remram44/rabbitmq:3.8.11
        securityContext:
          runAsUser: 999
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.password
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15692
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: auctus
    what: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: auctus
      what: redis
  template:
    metadata:
      labels:
        app: auctus
        what: redis
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: redis
        image: redis:6.2
        securityContext:
          runAsUser: 999
        args: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/redis
      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: redis.conf
            path: redis.conf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lazo
  labels:
    app: auctus
    what: lazo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: auctus
      what: lazo
  template:
    metadata:
      labels:
        app: auctus
        what: lazo
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: lazo
        image: registry.gitlab.com/vida-nyu/auctus/lazo-index-service:0.7.1
        env:
        - name: DATABASE
          value: elasticsearch
        - name: PORT
          value: "50051"
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_INDEX
          valueFrom:
            configMapKeyRef:
              name: config
              key: elasticsearch_lazo_index
        - name: JAVA_OPTS
          value: "-Xmx2g -Xms2g"
        ports:
        - containerPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: auctus
    what: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: auctus
      what: frontend
  template:
    metadata:
      labels:
        app: auctus
        what: frontend
    spec:
      containers:
      - name: nginx
        image: auctus_frontend
        imagePullPolicy: IfNotPresent
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: api_url
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  labels:
    app: auctus
    what: apiserver
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: auctus
      what: apiserver
  template:
    metadata:
      labels:
        app: auctus
        what: apiserver
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: apiserver
        image: auctus_apiserver
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              name: config
              key: log.format
        - name: OTEL_TRACES_EXPORTER
          valueFrom:
            configMapKeyRef:
              name: config
              key: otel.exporter
        - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: otel.jaeger.host
        - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: otel.jaeger.port
        - name: OTEL_EXPORTER_JAEGER_AGENT_SPLIT_OVERSIZED_BATCHES
          value: "1"
        - name: ELASTICSEARCH_HOSTS
          value: elasticsearch:9200
        - name: ELASTICSEARCH_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: elasticsearch_prefix
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.password
        - name: REDIS_HOST
          value: redis:6379
        - name: S3_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: s3.key
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: s3.secret
        - name: S3_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.url
        - name: S3_CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.client_url
        - name: S3_BUCKET_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.bucket_prefix
        - name: GCS_PROJECT
          valueFrom:
            configMapKeyRef:
              name: config
              key: gcs.project
        - name: GCS_CREDS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: gcs.creds
        - name: GCS_BUCKET_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: gcs.bucket_prefix
        - name: LAZO_SERVER_HOST
          value: lazo
        - name: LAZO_SERVER_PORT
          value: "50051"
        - name: NOMINATIM_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: nominatim_url
        - name: AUCTUS_REQUEST_WHITELIST
          valueFrom:
            configMapKeyRef:
              name: config
              key: request_whitelist
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: frontend_url
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: api_url
        - name: CUSTOM_FIELDS
          valueFrom:
            configMapKeyRef:
              name: config
              key: custom_fields
        ports:
        - containerPort: 8002
        volumeMounts:
        - mountPath: /cache
          name: cache
        - mountPath: /usr/src/app/lib_geo/data
          name: geo-data
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          periodSeconds: 1
          failureThreshold: 2
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: cache
      - name: geo-data
        persistentVolumeClaim:
          claimName: geo-data
          readOnly: true
      terminationGracePeriodSeconds: 600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  labels:
    app: auctus
    what: coordinator
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: auctus
      what: coordinator
  template:
    metadata:
      labels:
        app: auctus
        what: coordinator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: web
        image: auctus_coordinator
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              name: config
              key: log.format
        - name: ELASTICSEARCH_HOSTS
          value: elasticsearch:9200
        - name: ELASTICSEARCH_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: elasticsearch_prefix
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.password
        - name: S3_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: s3.key
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: s3.secret
        - name: S3_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.url
        - name: S3_CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.client_url
        - name: S3_BUCKET_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.bucket_prefix
        - name: GCS_PROJECT
          valueFrom:
            configMapKeyRef:
              name: config
              key: gcs.project
        - name: GCS_CREDS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: gcs.creds
        - name: GCS_BUCKET_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: gcs.bucket_prefix
        - name: LAZO_SERVER_HOST
          value: lazo
        - name: LAZO_SERVER_PORT
          value: "50051"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: admin.password
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: frontend_url
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: api_url
        - name: CUSTOM_FIELDS
          valueFrom:
            configMapKeyRef:
              name: config
              key: custom_fields
        ports:
        - containerPort: 8003
        volumeMounts:
        - mountPath: /cache
          name: cache
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: cache
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cache-cleaner
  labels:
    app: auctus
    what: cache-cleaner
spec:
  selector:
    matchLabels:
      app: auctus
      what: cache-cleaner
  template:
    metadata:
      labels:
        app: auctus
        what: cache-cleaner
    spec:
      securityContext:
        runAsNonRoot: true
      initContainers:
      - name: fix-permissions
        image: busybox
        securityContext:
          runAsNonRoot: false
        command: ["sh", "-c", "chown -R 998 /cache"]
        volumeMounts:
        - mountPath: /cache
          name: cache
      containers:
      - name: cleaner
        image: auctus_cache_cleaner
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              name: config
              key: log.format
        - name: MAX_CACHE_BYTES
          valueFrom:
            configMapKeyRef:
              name: config
              key: max_cache_bytes
        volumeMounts:
        - mountPath: /cache
          name: cache
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiler
  labels:
    app: auctus
    what: profiler
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 2
  selector:
    matchLabels:
      app: auctus
      what: profiler
  template:
    metadata:
      labels:
        app: auctus
        what: profiler
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: profiler
        image: auctus_profiler
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              name: config
              key: log.format
        - name: OTEL_TRACES_EXPORTER
          valueFrom:
            configMapKeyRef:
              name: config
              key: otel.exporter
        - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: otel.jaeger.host
        - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: otel.jaeger.port
        - name: OTEL_EXPORTER_JAEGER_AGENT_SPLIT_OVERSIZED_BATCHES
          value: "1"
        - name: ELASTICSEARCH_HOSTS
          value: elasticsearch:9200
        - name: ELASTICSEARCH_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: elasticsearch_prefix
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.password
        - name: S3_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: s3.key
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: s3.secret
        - name: S3_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.url
        - name: S3_CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.client_url
        - name: S3_BUCKET_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.bucket_prefix
        - name: GCS_PROJECT
          valueFrom:
            configMapKeyRef:
              name: config
              key: gcs.project
        - name: GCS_CREDS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: gcs.creds
        - name: GCS_BUCKET_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: gcs.bucket_prefix
        - name: LAZO_SERVER_HOST
          value: lazo
        - name: LAZO_SERVER_PORT
          value: "50051"
        - name: NOMINATIM_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: nominatim_url
        - name: AUCTUS_REQUEST_WHITELIST
          valueFrom:
            configMapKeyRef:
              name: config
              key: request_whitelist
        volumeMounts:
        - mountPath: /cache
          name: cache
        - mountPath: /usr/src/app/lib_geo/data
          name: geo-data
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: cache
      - name: geo-data
        persistentVolumeClaim:
          claimName: geo-data
          readOnly: true
