---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secrets
data:
  # Those values need to be encoded in base64
  amqp.user: YXVjdHVz # "auctus"
  amqp.password: YXVjdHVz # "auctus"
  admin.password: YXVjdHVz # "auctus"
  s3.key: ""
  s3.secret: ""
  gcs.creds: ""
