---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: auctus
    what: elasticsearch
spec:
  selector:
    app: auctus
    what: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: auctus
    what: rabbitmq
spec:
  selector:
    app: auctus
    what: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  labels:
    app: auctus
    what: rabbitmq
spec:
  selector:
    app: auctus
    what: rabbitmq
  ports:
  - protocol: TCP
    port: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: auctus
    what: redis
spec:
  selector:
    app: auctus
    what: redis
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: lazo
  labels:
    app: auctus
    what: lazo
spec:
  selector:
    app: auctus
    what: lazo
  ports:
  - protocol: TCP
    port: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: auctus
    what: frontend
spec:
  selector:
    app: auctus
    what: frontend
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    app: auctus
    what: coordinator
spec:
  selector:
    app: auctus
    what: coordinator
  type: NodePort
  ports:
  - protocol: TCP
    port: 8003
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  labels:
    app: auctus
    what: apiserver
spec:
  selector:
    app: auctus
    what: apiserver
  type: NodePort
  ports:
  - protocol: TCP
    port: 8002
    nodePort: 30002
