---
apiVersion: v1
kind: ConfigMap
metadata:
  name: socrata
  labels:
    app: auctus
data:
  socrata.json: |
    [
      {"url": "data.cityofnewyork.us"},
      {"url": "finances.worldbank.org"}
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socrata
  labels:
    app: auctus
    what: socrata
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: auctus
      what: socrata
  template:
    metadata:
      labels:
        app: auctus
        what: socrata
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: socrata
        image: auctus_socrata
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTICSEARCH_HOSTS
          value: elasticsearch:9200
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.password
        - name: LAZO_SERVER_HOST
          value: lazo
        - name: LAZO_SERVER_PORT
          value: "50051"
        volumeMounts:
        - name: config
          mountPath: /usr/src/app/socrata.json
          subPath: socrata.json
      volumes:
      - name: config
        configMap:
          name: socrata
