---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datasets
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: geo-data
spec:
  storageClassName: ""
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 300Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-synonyms
spec:
  storageClassName: ""
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Mi
