---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache
  labels:
    type: local
    app: auctus
    what: cache
spec:
  storageClassName: "manual"
  capacity:
    storage: 55Gi
  accessModes:
  - ReadWriteMany
  local:
    path: "/var/lib/auctus/prod/cache"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: auctus-prod-cache-volume
              operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
spec:
  storageClassName: "manual"
  volumeName: cache
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 55Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geo-data
spec:
  accessModes:
  - ReadOnlyMany
  - ReadWriteOnce
  resources:
    requests:
      storage: 2.5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-synonyms
spec:
  accessModes:
  - ReadOnlyMany
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
