[tool.poetry]
name = "datamart"
version = "0.8"
description = "Datamart system meta-package"

license = "Apache-2.0"

authors = [
    "Remi Rampin <remi.rampin@nyu.edu>",
]

repository = "https://gitlab.com/ViDA-NYU/datamart/datamart"
homepage = "https://auctus.vida-nyu.org/"

keywords = ["datamart"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Information Analysis",
]

packages = []

include = []

[tool.poetry.dependencies]
python = "^3.7"
datamart-profiler = {path = "./lib_profiler"}
datamart-materialize = {path = "./lib_materialize"}
datamart-augmentation = {path = "./lib_augmentation"}
datamart-geo = {path = "lib_geo"}
datamart-core = {path = "./lib_core"}
datamart-coordinator-service = {path = "./coordinator"}
datamart-profiler-service = {path = "./profiler"}
datamart-api-service = {path = "./apiserver"}
datamart-noaa_discovery-service = {path = "./discovery/noaa"}
datamart-socrata-discovery-service = {path = "./discovery/socrata"}
datamart-zenodo-discovery-service = {path = "./discovery/zenodo"}
datamart-uaz_indicators-service = {path = "./discovery/uaz_indicators"}
datamart-worldbank-discovery-service = {path= "./discovery/worldbank"}

[tool.poetry.dev-dependencies]
flake8 = "*"
PyYaml = "*"
requests = "*"
coverage = "*" # Keep it in sync with Dockerfiles for CI
jsonschema = ">=3.0,<4"
readme_renderer = "*"
Sphinx = "*"
sphinx-rtd-theme = "^0.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
